---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pilot-controller
rules:
- apiGroups: ["harbor.vmware.com"]
  resources: ["pilotscans"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pilot-controller
subjects:
- kind: User
  name: system:serviceaccount:pilotcontroller:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pilot-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pilot-controller
  namespace: pilotcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilot-controller
  template:
    metadata:
      labels:
        app: pilot-controller
    spec:
      containers:
      - name: controller
        image: ctracey/pilot-controller
        command: ["pilot", "-d"]

