apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: testpod
spec:
  containers:
  - name: myapp-container
    image: harbor.humblelab.com/library/org-api:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
